### ISSUE TITLE
No completes available in the package..

### ISSUE THREAD

**Issue by prajush** [tinode/android-example#1]
E:\GitHub\android-example-master\app\src\main\java\co\tinode\tindroid\MessagesListAdapter.java
Error:(118, 44) error: cannot find symbol variable bubble_r
Error:(118, 66) error: cannot find symbol variable bubble_l
Error:(121, 48) error: cannot find symbol variable bubble_r
Error:(121, 70) error: cannot find symbol variable bubble_l
Error:(126, 48) error: cannot find symbol variable bubble_r_z
Error:(126, 72) error: cannot find symbol variable bubble_l_z
Error:(131, 48) error: cannot find symbol variable bubble_r_z
Error:(131, 72) error: cannot find symbol variable bubble_l_z
Error:(136, 48) error: cannot find symbol variable bubble_r
Error:(136, 70) error: cannot find symbol variable bubble_l

**Comment by or-else** [comment]
Acknowledged. Will fix on Monday. Thanks.

**Comment by or-else** [comment]
Done: a61667d
