### ISSUE TITLE
what's the logic of loginToken

### ISSUE THREAD

**Issue by ChenZhaobin** [tinode/android-example#2]
In method : loginToken(String token, Credential[] creds)
what does Credential[] mean?
I want use token generated  by my other user system ,what can be the logic ?

**Comment by or-else** [comment]
> what does Credential[] mean?

It's an optional parameter which allows you to validate credentials, like email or phone or captcha.

> I want use token generated by my other user system ,what can be the logic ?

See conversation here: https://github.com/tinode/chat/issues/79

**Comment by ChenZhaobin** [comment]
@or-else  how can I generate a token like this: [8:UID][4:expires][2:authLevel][2:serial-number][4:feature-bits][32:signature]
Is there an example of JS or android ?

**Comment by or-else** [comment]
No update in two days. I assume you have figured it out, so I'm closing the issue.
