### ISSUE TITLE
Android search contacts enhancement.

### ISSUE THREAD

**Issue by jinfagang** [tinode/android-example#3]
Hi, I think this feature can be considered:

- People can search people to start 1-1 chat, not only within the phone contacts book, this will be more convenient for people to use: I mean wider use, not so close but more open.

**Comment by or-else** [comment]
You already can find new people by adding them to your contacts:
![screenshot_1525122564](https://user-images.githubusercontent.com/5938143/39450506-67972e1c-4c80-11e8-9514-50faafd6d6ab.png)
That's how WhatsApp, Telegram, and WeChat work. Why isn't it sufficient for your case?

**Comment by jinfagang** [comment]
This button I clicked, seems it's using for adding new contacts to your local Phone Contacts book. I saw the JS client, I can search people via: `email: 11@11.com` or `tel:14245263`, and there are people on list if it exist in our database, then just click it, a new chat can be open. This is  more convenient I think.

**Comment by or-else** [comment]
I think the existing messengers got it right. You don't add new contacts often. You have most people in your address book, then you talk to the same ones all the time. If you get a new contact, you get add it to the address book and make it available in all apps. 

What is the use case that you have in mind which is different from WeChat & other messengers?

**Comment by jinfagang** [comment]
Yeah you are right, what I am saying it the same function as: such as WeChat, it can be done to search people by their IDs. For instance, I got an ID from internet or other peoples sharing, If I adding it into local contacts book seems to be a HUGE workload, write their names, phone number etc. But with an only uuid such as Tinode ID or user registered Phone, search it and got him, then click to chat, is that convenient and more fun to play with

**Comment by or-else** [comment]
OK, that makes sense. Something like _Start chat by ID_, like the one in JS.

**Comment by or-else** [comment]
Done - `devel` branch now has the feature.

**Comment by jinfagang** [comment]
Waoh! So fast!!

**Comment by jinfagang** [comment]
I think now it's pretty good for people to use
