### ISSUE TITLE
first login will break the connection

### ISSUE THREAD

**Issue by 7a6ac0** [tinode/android-example#4]
When I use username/password login to the server at the first time, the connection between client and server will disconnect.
```
05-17 03:05:23.606 1003-1098/co.tinode.tindroid D/Connection: onDisconnected for '' (1000); reconnecting=false
05-17 03:05:23.607 1003-1098/co.tinode.tindroid D/UiUtils: Network error
```
In [SyncAdapter.java](https://github.com/tinode/android-example/blob/master/app/src/main/java/co/tinode/tindroid/account/SyncAdapter.java) line 128, I commented out the code ```tinode.disconnect();```. And it will not break the connection.

**Comment by or-else** [comment]
Thanks for the report. It's been fixed in devel: https://github.com/tinode/android-example/commit/99a6c5547e2cf003689885fd3bdcc114091e0cd7#diff-6a4278178549615483b36a57f8ae3f8d
